### ISSUE TITLE
Translation issue on 'page_or_link' type

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/MenuCRUD#55] opened 2020-03-11 04:29 UTC
This special type causing `HasTranslations` traits cannot work properly
```
$this->crud->addField([
                'name' => ['type', 'link', 'page_id'],
                'label' => 'Type',
                'type' => 'page_or_link',
                'page_model' => '\Backpack\PageManager\app\Models\Page',
            ]);
```

`name` should not be array

`Argument 1 passed to App\Models\BackpackMenu::isTranslatableAttribute() must be of the type string, array given, called in `

**Comment by tabacitu** [comment] 2020-03-11 05:45
Hi @kiddtang ,

Could you please rephrase to make sure I understand? 

1) What did you try to do? Did you try to make the "type" attribute translatable, and use the page_or_link field for it? Or did you make another attribute on that model translatable? A copy-paste of the CrudController would help here.

2) What operation is this error for? Create or Update?

Cheers!

**Comment by kiddtang** [comment] 2020-03-11 05:53
@tabacitu Sorry for insufficient info. 
I extend the Model & CRUD controller in order to make the menu in multilingual

```
namespace App\Models;

use Backpack\MenuCRUD\app\Models\MenuItem;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;

class BackpackMenu extends MenuItem
{
    use HasTranslations;

    protected $translatable = ['name'];
```
i just copy paste your fields definitions and i found the `name` cannot be array

https://github.com/Laravel-Backpack/MenuCRUD/blob/8935f84d111562d55c1770315bac3658128ca734/src/app/Http/Controllers/Admin/MenuItemCrudController.php#L52

Then i change to this, it works now.
```
            $this->crud->addField([
                'name'       => 'type_link_page_id',
                'label'      => 'Type',
                'type'       => 'page_or_link',
                'page_model' => '\Backpack\PageManager\app\Models\Page',
            ]);
```

**Comment by spektakl** [comment] 2020-05-06 10:39
Hello, same problem here also. with the exact same steps as @kiddtang

**Comment by spektakl** [comment] 2020-05-11 15:44
Thanks @tabacitu for addressing this issue! ;)

**Comment by tabacitu** [comment] 2020-05-12 04:17
Hmm... have you upgraded to v4.0 or v4.1 from Backpack 3.x? If so, you might have an old `page_or_link` field type published, that doesn't have the fix. 

1) What's the output of your `php artisan backpack:version`?
2) Do you have this file - `resources/views/vendor/backpack/crud/fields/page_or_link.blade.php`?

**Comment by spektakl** [comment] 2020-05-12 06:48
Hi! Yes, I've upgraded from 4 to 4.1 recently:

1) php artisan backpack:version returns version 4.1.2@7084182b38bff6b19624788ff143bb249ecdc758
2) No, I did not have that file `resources/views/vendor/backpack/crud/fields/page_or_link.blade.php`, but I copied it there from `/vendor`, and now is there, despite I think this does not change anything...

Maybe deleting vendor and doing `composer install` again?

This is a screenshot of the project:

<img width="1049" alt="Captura de pantalla 2020-05-12 a las 8 44 32" src="https://user-images.githubusercontent.com/45669520/81647408-41681200-942d-11ea-8167-d443059c5f5e.png">

And this is a screenshot of the error that returns when executing the code:

<img width="1265" alt="Captura de pantalla 2020-05-12 a las 8 44 53" src="https://user-images.githubusercontent.com/45669520/81647454-53e24b80-942d-11ea-8b63-d1e86cf74253.png">

Thanks!

**Comment by spektakl** [comment] 2020-05-19 11:13
Hi!

I did these steps to try to fix this but without success :(

1. Created the file in `resources/views/vendor/backpack/crud/fields/page_or_link.blade.php`
2. Copied there all the content from [https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/fields/page_or_link.blade.php](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/fields/page_or_link.blade.php)
3. Cleared all Laravel caches (views, config, etc).

But the issue is still appearing.

I understand that you already fixed the issue in a current release right? What am I missing, then?

Thanks!

**Comment by deepaksp** [comment] 2020-05-26 07:55
this issue is caused by translatable icon view as it check column is translatable or not  without checking column is string or array!
create new translatable icon and check for array field and loop through it
crud>fields>inc>translatable_icon.blade.php

**Comment by spektakl** [comment] 2020-05-26 09:54
Thanks @deepaksp 

I added the file `resources/views/vendor/backpack/crud/fields/inc/translatable_icon.blade.php` with this content:

`
@php
    $theField = $field['name'];
    if (is_array($field['name'])) {
        $theName = '';
        $counter = 0;
        foreach($theField as $field) {
            if ($counter > 0) $theName.='_';
            $theName.=$field;
            $counter++;
        }
        $theField = $theName;
    }
@endphp

@if (method_exists($crud->model, 'isTranslatableAttribute') && ($crud->model->isTranslatableAttribute($theField) || (isset($field['store_in']) ? $crud->model->isTranslatableAttribute($field['store_in']) : false)) && config('backpack.crud.show_translatable_field_icon'))
<i class="la la-flag-checkered pull-{{ config('backpack.crud.translatable_field_icon_position') }}" style="margin-top: 3px;" title="This field is translatable."></i>
@endif
`

Somehow, it works now...

**Comment by pabloblazquez** [comment] 2020-06-03 15:58
Based on the concept of the previous solution, I have made my own so that the flag icon appears when the 'page_or_link' field is multi-language.

```
@php
    $field_name_is_translatable = false;
    foreach((array) $field['name'] as $field_name){
        if($crud->model->isTranslatableAttribute($field_name)) {
            $field_name_is_translatable = true;
        }
    }
@endphp

@if (method_exists($crud->model, 'isTranslatableAttribute') && ($field_name_is_translatable || (isset($field['store_in']) ? $crud->model->isTranslatableAttribute($field['store_in']) : false)) && config('backpack.crud.show_translatable_field_icon'))
    <i class="la la-flag-checkered pull-{{ config('backpack.crud.translatable_field_icon_position') }}" style="margin-top: 3px;" title="This field is translatable."></i>
@endif
```

**Comment by tabacitu** [comment] 2020-07-09 09:05
Awesome! Thanks a lot @pabloblazquez - would you care to create a PR with it - it looks like it would be a good fix inside the `page_or_link` field type right?

**Comment by pxpm** [comment] 2020-10-22 12:55
Hello guys.

Sorry for the amount of time it took to get into this. 

I'v just submited the PR https://github.com/Laravel-Backpack/CRUD/pull/3276 that would fix this issue.

Let me know if it fixed for your guys in the PR thread, in meanwhile I am going to close this.

Wish you guys the best, and thank you very much in helping debug this issue and providing fixes for it,

Pedro

**Closed by pxpm** 2020-10-22 12:55 UTC
Labels: bug
