### ISSUE TITLE
error while adding new menu

### ISSUE THREAD

**Issue by zunky44** [Laravel-Backpack/MenuCRUD#5] opened 2016-09-12 08:16 UTC
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'parent_id' at row 1 (SQL: insert into `menu_items` (`name`, `parent_id`, `type`, `link`, `updated_at`, `created_at`) values (Home, , external_link, http://localhost:8000/, 2016-09-12 08:15:42, 2016-09-12 08:15:42))

**Comment by tabacitu** [comment] 2016-09-12 08:29
Hi @zunky44 ,

Thank you, just tested, this is because Laravel 5.3 ships with MySQL strict=true, whereas Laravel 5.2 did not. Until we fix this, you can set strict=false in your config/database.php and everything will work.

Cheers!

**Comment by tabacitu** [comment] 2016-09-12 08:55
The issue is now fixed in Backpack\CRUD v3.1.2 - please run a ```composer update``` to get the latest version. Then you can use MySQL strict mode ON without issues.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Closed by tabacitu** 2016-09-12 08:55 UTC
